import Vue from 'vue'
import { Search, Popup, CellGroup, PullRefresh, List, Tab, Tabs, Dialog, Button, NavBar, Form, Field, Icon, Toast, CountDown, Tabbar, TabbarItem, Image as VanImage, Grid, GridItem, Cell } from 'vant'


Vue.use(Button)
Vue.use(NavBar)
Vue.use(Form)
Vue.use(Field)
Vue.use(Icon)
Vue.use(Toast)
Vue.use(CountDown)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(VanImage)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(Cell)
Vue.use(Dialog)
Vue.use(Tab)
Vue.use(Tabs)
Vue.use(List)
Vue.use(PullRefresh)
Vue.use(CellGroup)
Vue.use(Popup)
Vue.use(Search)